 # Generated by Django 5.0.14 on 2026-01-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('advanced', 'Advanced Perm'), ('pr0', 'Pro Perm'), ('basic', 'Basic Perm')],
            },
        ),
    ]
