# Generated by Django 5.0.14 on 2026-01-17 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="description",
        ),
    ]
