# Generated by Django 5.0.14 on 2026-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_subscription_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
