# Generated by Django 5.0.14 on 2026-01-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_subscription_stripe_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("mont", "Monthly"), ("year", "Yearly")],
                        default="mont",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
    ]
