# Generated by Django 5.0.14 on 2026-01-23 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
