# Generated by Django 5.0.14 on 2026-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0015_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionprice",
            old_name="stripe_customer_id",
            new_name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="stripe_product_id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=-1),
        ),
    ]
