# Generated by Django 5.0.14 on 2026-01-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_rename_stripe_customer_id_subscriptionprice_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Featured for pricing, separate by line', null=True),
        ),
    ]
